package com.girish.mulithread;
class MyThread1 extends Thread
{
	/*public void start()
	{	
		super.start();//By using this type first it runs the start method after Thread class run method will be excuted
		System.out.println("This is MyThread1 class start method");
	}*/
	public void run()
	{
		//System.out.println("This is MyThread1 class run method");
		for(int i=0;i<=10;i++)
		{
			System.out.println("Thread Child Thread");
		}
	}
	
}
class MyThread2  implements Runnable
{
	
	int ver;
	public MyThread2(int var)
	{
		//System.out.println(var);
	}

		
	public void run() {
		
		for(int i=0;i<=10;i+=2)
		{
			System.out.println("Runnable Chaild Thread");
		}
		/*try
		{
			Thread.sleep(10);
			System.out.println("This is MyThread2 class run method");
			
		} 
		catch (InterruptedException e) 
		{
			e.printStackTrace();
		}
		*/
		
	}
	
	
}

public class OneThread //extends Thread
{
	public static void main(String[] args) 
	{
		/*MyThread1 mt1=new MyThread1();
		mt1.setPriority(10);
		mt1.start();
		//mt1.start();
*/		
		System.out.println("main called");
		
		
		MyThread2 mt2=new MyThread2(100);
		Thread t=new Thread(mt2);
		//t.setPriority(10);
		t.start();
		
		for(int i=0;i<=3;i++)
		{
			System.out.println("Main Thread");
		}
			
		
		/*Thread t1=new Thread(mt2);
		t1.start();*/
		
		/* //Every thread in java has some name it is provided by developer or default name generated by JVM
		System.out.println(Thread.currentThread().getName());//main
		Thread.currentThread().setName("girish Runnable");
		System.out.println(Thread.currentThread().getName());//girish runnable
*/		
		//t1.start();//new thread will be created it is executed MyThread run() Method
		//t.run(); It calls ordinary run method
		
		
		/*for(int j=1;j<=10;j+=2)
		{
			try {
				Thread.sleep(250);
				System.out.println(j+"  ");
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		}
		*/
		
	}

}
